services:
  # database:
  #   image: "postgres:9.6-alpine"
  #   container_name: kanban-postgres
  #   volumes:
  #     - kanban-data:/var/lib/postgresql/data
  #   ports:
  #     - 5432:5432
  #   environment:
  #     - POSTGRES_DB:kanban
  #     - POSTGRES_USER:kanban
  #     - POSTGRES_PASSWORD:kanban

  backend:
    build: ./backend
    container_name: recipe-backend
    # environment:
    #   - DB_SERVER=kanban-postgres
    ports:
      - 5000:5000
    # links:
    #   - kanban-postgres

  frontend:
    build: ./frontend
    container_name: recipe-frontend
    ports:
      - 8080:8080
    links:
      - backend


# volumes:
#   kanban-data: