services:
  backend:
    build: ./backend
    ports:
      - 5000:5000
    volumes:
      - ./backend:/usr/src/backend
    command: python3 -m flask run --host=0.0.0.0 --debug
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - 8080:8080
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/frontend
      - /usr/src/frontend/node_modules/
    environment:
      # Live reload bs
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: npm run dev